name: Auto PR from dev to stg

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create pull request from dev to stg
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'dev'
          destination_branch: 'stg'
          pr_title: 'Auto PR: Merge dev into stg'
          pr_body: 'This PR was automatically created by a GitHub Action on push to dev.'
          github_token: ${{ secrets.PAT }}
